networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.55.1
        subnet: 192.168.55.0/24
      driver: default
services:
  node0:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 0
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.10
    ports:
    - 9090:9090
  node1:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 1
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.11
    ports:
    - 9091:9091
  node2:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 2
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.12
    ports:
    - 9092:9092
  node3:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 3
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.13
    ports:
    - 9093:9093
  node4:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 4
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.14
    ports:
    - 9094:9094
version: '3.7'
x-common-variables:
  EMPTY: null
  TOPOLOGY: topologies/blockchain.yaml
